const ModalPaths = [
  '/signup',
  '/login',
  '/pricing/signup',
  '/pricing/login',
  '/forbidden/signup',
  '/forbidden/login',
  '/unauthorized/signup',
  '/unauthorized/login',
  '/start/create-organization',
  '/reservations/reserve',
  '/reservations/:reservationId/days/:timeRangeId/cancel-day',
  '/reservations/:reservationId/days/:timeRangeId/reserve',
  '/manage/organizations/:organizationId/members/email-confirmation',
  '/manage/organizations/:organizationId/members/invite',
  '/manage/organizations/:organizationId/members/invite-upgrade',
  '/manage/organizations/:organizationId/members/:membershipId/email-confirmation',
  '/manage/organizations/:organizationId/members/:membershipId/invite',
  '/manage/organizations/:organizationId/members/:membershipId/invite-upgrade',
  '/manage/organizations/:organizationId/members/invitations/:invitationId/invite',
  '/manage/organizations/:organizationId/members/invitations/:invitationId/cancel-invite',
  '/manage/organizations/:organizationId/members/:membershipId/edit-roles',
  '/manage/organizations/:organizationId/members/:membershipId/remove-member',
  '/manage/organizations/:organizationId/desks/locations/:locationId/delete-location',
  '/manage/organizations/:organizationId/desks/locations/:locationId/add-space',
  '/manage/organizations/:organizationId/desks/locations/:locationId/add-space-upgrade',
  '/manage/organizations/:organizationId/desks/add-location',
  '/manage/organizations/:organizationId/desks/add-location-upgrade',
  '/manage/organizations/:organizationId/desks/locations/:locationId/add-location',
  '/manage/organizations/:organizationId/desks/locations/:locationId/add-location-upgrade',
  '/manage/organizations/:organizationId/desks/locations/:locationId/spaces/:spaceId/add-location',
  '/manage/organizations/:organizationId/desks/locations/:locationId/spaces/:spaceId/add-location-upgrade',
  '/manage/organizations/:organizationId/desks/locations/:locationId/edit-location-name',
  '/manage/organizations/:organizationId/desks/locations/:locationId/edit-location-image',
  '/manage/organizations/:organizationId/desks/locations/:locationId/remove-location-image',
  '/manage/organizations/:organizationId/desks/locations/:locationId/edit-location-address',
  '/manage/organizations/:organizationId/desks/locations/:locationId/remove-location-address',
  '/manage/organizations/:organizationId/desks/locations/:locationId/spaces/:spaceId/add-desk',
  '/manage/organizations/:organizationId/desks/locations/:locationId/spaces/:spaceId/add-desk-upgrade',
  '/manage/organizations/:organizationId/desks/locations/:locationId/spaces/:spaceId/delete-desk',
  '/manage/organizations/:organizationId/desks/locations/:locationId/spaces/:spaceId/delete-space',
  '/manage/organizations/:organizationId/desks/locations/:locationId/spaces/:spaceId/edit-space-name',
  '/schedule/organizations/:organizationId/locations/:locationId/reserve',
  '/manage/organizations/:organizationId/organization/edit-cleaning',
  '/manage/organizations/:organizationId/organization/edit-organization-name',
  '/manage/organizations/:organizationId/organization/edit-organization-icon',
  '/manage/organizations/:organizationId/organization/remove-organization-icon',
  '/manage/organizations/:organizationId/organization/delete-organization',
  '/change-plan/:organizationId/meet-quota',
  '/settings/change-password',
  '/settings/delete-account',
  '/settings/edit-avatar',
  '/settings/remove-avatar',
  '/settings/edit-name',
  '/settings/create-organization',
]

export const upOnePath = (path: string) => {
  const index = path.lastIndexOf('/')
  return path.substr(0, index)
}

export default ModalPaths
