export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID || ''
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET || ''
export const GOOGLE_API_KEY = process.env.GOOGLE_API_KEY || ''
export const MONGO_URI = process.env.MONGO_URI || ''
export const COOKIE_KEY = process.env.COOKIE_KEY || ''
export const MAILGUN_API_KEY = process.env.MAILGUN_API_KEY || ''
export const STRIPE_API_KEY = process.env.STRIPE_API_KEY || ''
export const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET || ''
export const CAPTCHA_SECRET_KEY = process.env.CAPTCHA_SECRET_KEY || ''
export const GOOGLE_APPLICATION_CREDENTIALS =
  process.env.GOOGLE_APPLICATION_CREDENTIALS || ''
